### ISSUE TITLE
Switch to a non-root user

### ISSUE THREAD

**Issue by digitalronin** [ministryofjustice/cloud-platform-tools-image#24]
The tools image runs everything as root. This means we can't launch a container based on it in our kubernetes cluster. 

Alter the image to use a non-root user. This will also require changes to the [cluster build script](https://github.com/ministryofjustice/cloud-platform-infrastructure/blob/master/create-cluster.rb) (which assumes `/root` is the user's home directory), and also changes to the Dockerfile, which puts a lot of stuff into /root.

**Comment by jasonBirchall** [comment]
aged out as this is no longer needed.
