### ISSUE TITLE
Circle CI cannot access git binary on the image

### ISSUE THREAD

**Issue by willc-work** [ministryofjustice/cloud-platform-tools-image#73]
When I deploy via circle ci I get a message during the Checkout Code section that says:

`Either git or ssh (required by git to clone through SSH) is not installed in the image. Falling back to CircleCI's native git client but the behaviour may be different from official git.`

First noticed during an upgrade to helm version 3 using the image tagged with 1.23 but I tested again with version 1.25 this morning with the same result.

See here for example of the issue:
https://app.circleci.com/pipelines/github/ministryofjustice/laa-apply-for-legal-aid/5461/workflows/3a8e131e-a407-42ab-8b10-ad8ac0a5c2c6/jobs/39942

**Comment by jasonBirchall** [comment]
Sorry for closing before a message. This has aged out and I believe it may have resolved itself - I seem to remember having a convo about it in slack.
